---
title: "R Notebook"
output: html_notebook
---



## Author: OA Lab, NWFSC
### Title: Aquarium Temperature Investigation: Temperature SubSelectScript.R 
### Date: April-May 2020

# Aquarium Temperature Investigation
R script below will subselect and plot temperature data for MOATs
Overall goal is to determine if MOATs (per treatment) are true replicates


```{r}
#*********************************
##Libraries
#********************************* 
library(shiny)
library(tidyverse)
library(stringr)
library(readxl)
library(readr)
library(tidyr)
library(data.table)
library(lubridate)
library(violinmplot)
library(vioplot)
library(yarrr)
library(datapasta)
library(reprex)
library(miniUI)
library(gridExtra)
```



## Outline 
(Current as of 2020.06.25)

* 1.) Working Directory
* 2.) Spolling Data into one CSV 
* 3.) Creating the Dataframe "dml"
* 4.) Setting a new working directory
* 4.) Creating dateTime objects 
* 5.) Creating Treatment Variables
* 6.) Creating Night and Day Periods
* 7.) Insitu data
* 8.) Cleaning up dml "Cdml"
* 9.) Framing filters for Cdml
* 10.) Temperature "Jumps"
* 11.) Calculating averages by treatment & day/night
* 12.) Summary & Group by Cdml
* 13.) Plots Boxplots & timeseries
* 14.) Duration between conditions- Histogram & Cummulative Distribtuion Plot  section
* 15.) aTemp bands investig.
* 16.) Share-able tibbles & reprex readiness  


#1.) Working Directory

Inside the working directory (folder) are CSV files generated after using the moats graph app
[Link to moats.Graph.app](http://github.com/pmcelhany/moatsGraphs.git)
Moving average window (nObs) set to 4. This results in the observations being averaged into a 24second timeframe. CSVs were created for each moats: M01, M02, M03, M04, M05, M06, M07, M08, M09, M10, M11, M12, M13. Files are also available on the OA Google drive. [OA Drive for MOATS data](https://drive.google.com/open?id=13a2hk1a9I9gRIgf2Xyl1dSYDf5vnyYvs)


